added PHP 8 support
arnegroskurth/TempFile pull request #5
Opened 2021-10-03 18:09 UTC by oburk

2021-10-03 18:43 UTC, oburk commented
**ready for review**

2021-10-22 09:27 UTC, arnegroskurth requested changes

2021-10-22 09:27 UTC, arnegroskurth commented on composer.json
> +    "symfony/http-foundation": "^5.0"
Any reason to remove support for the other versions?

2021-10-22 09:27 UTC, arnegroskurth commented on composer.json
> +    "php": "^7.3 || ^8.0",
It seems like this library does still support 5.x - any reason to remove that support?

2021-10-23 12:13 UTC, oburk commented on composer.json
> +    "symfony/http-foundation": "^5.0"
I re added the constrains here

2021-10-23 12:14 UTC, oburk commented on composer.json
> +    "php": "^7.3 || ^8.0",
PHPUnit9 requires PHP >= 7.3 and I had problems with running PHPUnit 5. Now I add a new Travis CI job. Please check it again.

2021-10-24 12:32 UTC, arnegroskurth approved these changes

2021-10-24 12:32 UTC, merged